package wli.hibernate.db;

// Generated Aug 17, 2011 9:35:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private int id;
	private int age;
	private String firstname;
	private String lastname;
	private Set events = new HashSet(0);

	public Person() {
	}

	public Person(int age, String firstname, String lastname, Set events) {
		this.age = age;
		this.firstname = firstname;
		this.lastname = lastname;
		this.events = events;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
