package wli.hibernate.db;

// Generated Aug 17, 2011 9:35:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private int id;
	private Date date;
	private String title;

	public Event() {
	}

	public Event(Date date, String title) {
		this.date = date;
		this.title = title;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
